name: Deploy Backend to Railway

on:
  push:
    branches: [ main ]
    paths:
      - 'server.py'
      - 'api/**'
      - 'requirements.txt'
      - '.github/workflows/backend-deploy.yml'
      - 'railway.toml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Install Railway CLI
        run: npm install -g @railway/cli
        
      - name: Deploy to Railway
        run: |
          railway link ${{ secrets.RAILWAY_PROJECT_ID }}
          railway up --service ${{ secrets.RAILWAY_SERVICE_NAME }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
